language: csharp
mono: none
os: linux
dist: focal
dotnet: 5.0
branches:
  only:
    - master
    - develop
before_script:
  - chmod -R a+x scripts
  - chmod -R a+x src
script:
  - dotnet build -c release
  - ./scripts/pack.sh
notifications:
  email:
    on_success: never
    on_failure: always
